import Link from 'next/link';

export default function TermsOfService() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-zinc-50 font-sans dark:bg-black px-6">
      <main className="w-full max-w-3xl rounded-2xl bg-white/90 p-10 shadow-xl ring-1 ring-gray-200 dark:bg-zinc-900 dark:ring-zinc-700">
        <Link href="/" className="text-indigo-500 hover:text-indigo-700 mb-4 inline-block">
          ← Back to Home
        </Link>
        
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-6">
          Terms of Service
        </h1>

        <div className="prose prose-gray dark:prose-invert max-w-none">
          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">Service Usage</h2>
            <p className="mb-4">
              By using this Discussion Insight Analyzer, you agree to the following terms:
            </p>

            <h3 className="text-xl font-semibold mb-3">Data Processing</h3>
            <ul className="list-disc pl-6 space-y-2 mb-6">
              <li>Discussion post data is processed temporarily for analysis only</li>
              <li>Data is not stored permanently</li>
              <li>Data is not shared with third parties</li>
              <li>Data is not used for AI model training</li>
            </ul>

            <h3 className="text-xl font-semibold mb-3">Content Guidelines</h3>
            <ul className="list-disc pl-6 space-y-2 mb-6">
              <li>You must comply with the source platform's terms of service</li>
              <li>You are responsible for ensuring you have permission to analyze the content</li>
              <li>The service may refuse to process content that violates safety guidelines</li>
            </ul>

            <h3 className="text-xl font-semibold mb-3">Attribution</h3>
            <ul className="list-disc pl-6 space-y-2 mb-6">
              <li>All insights include proper attribution to source content</li>
              <li>Original source URLs and contributors are credited in the output</li>
            </ul>

            <h3 className="text-xl font-semibold mb-3">Limitations</h3>
            <ul className="list-disc pl-6 space-y-2 mb-6">
              <li>This service is provided "as is" without warranties</li>
              <li>We are not responsible for the accuracy of source content</li>
              <li>Analysis results are generated by AI and should be verified independently</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold mb-4">Contact</h2>
            <p>
              For questions about these terms, please contact [your contact information].
            </p>
          </section>

          <hr className="my-6 border-zinc-200 dark:border-zinc-700" />
          
          <p className="text-sm text-gray-500 dark:text-gray-400 italic">
            Last updated: [Date]
          </p>
        </div>
      </main>
    </div>
  );
}

